version: 0.0.{build}
environment:
  XAMARIN_COOKIE:
    secure: Ut8C5dcSVEh3A8IZHlj39DBV/bP4KCxzsnovjgt55gYc0OYlWQwP/fAwl7DFtdR4
  HOCKEYAPP_APP_ID:
    secure: qbJ09dkcmcsS8wznuDU6lNgt4h2htHhGLhGj1/V6SyIg97j31U51BNb5t3pDuMVF
  HOCKEYAPP_API_TOKEN:
    secure: j0zM29SX82jirzfqpDjMKLVDuGCtnnhjAlfCW9VW13WihwhSyfJTzRmmqb4pjojM
  ANDROID_KEYSTORE_ALIAS:
    secure: n8AJ+/2dLtjovNej5PHJ1g==
  ANDROID_KEYSTORE_PASSWORD:
    secure: AU+rxD9IAqrN12v1cbTCSmFfqsNq5HZELytgwv4WW80=
  ANDROID_KEYSTORE_PATH: Keystore\KawaiiGames.keystore
  ANDROID_PROJECT_PATH: Xmas-Hell\Xmas-Hell-Android
  ANDROID_PROJECT_FILENAME: Xmas-Hell-Android.csproj
install:
  - ps: '& ./Scripts/InstallDependencies.ps1'
before_build:
  - xamarin-component.exe restore "%ANDROID_PROJECT_PATH%\%ANDROID_PROJECT_FILENAME%"
  - nuget restore "%ANDROID_PROJECT_PATH%"\packages.config -PackagesDirectory "packages"
  - ps: '& ./Scripts/UpdateAndroidVersion.ps1'
build_script:
  - msbuild "%ANDROID_PROJECT_PATH%\%ANDROID_PROJECT_FILENAME%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:detailed /t:SignAndroidPackage /p:Configuration=Release /p:Platform=AnyCPU /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias="%ANDROID_KEYSTORE_ALIAS%" /p:AndroidSigningKeyPass="%ANDROID_KEYSTORE_PASSWORD%" /p:AndroidSigningKeyStore="%APPVEYOR_BUILD_FOLDER%\%ANDROID_KEYSTORE_PATH%" /p:AndroidSigningStorePass="%ANDROID_KEYSTORE_PASSWORD%"
  - rename "%APPVEYOR_BUILD_FOLDER%\%ANDROID_PROJECT_PATH%\bin\Android\AnyCPU\Release\io.noxalus.XmasHell-Signed.apk" "XmasHell-%APPVEYOR_BUILD_NUMBER%.apk"
artifacts:
  - path: '%ANDROID_PROJECT_PATH%\bin\Android\AnyCPU\Release\XmasHell-%APPVEYOR_BUILD_NUMBER%.apk'
    name: Xmas Hell
deploy_script:
  - ps: '& ./Scripts/AndroidHockeyAppUpload.ps1'